package com.hason.study.spring_cxf.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.hason.study.spring_cxf.webservice.HelloWorldWebService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-23T16:13:16.535+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "HelloWorldWebServiceImplService", 
                  wsdlLocation = "http://localhost:8080/spring-cxf/webservice/hello?wsdl",
                  targetNamespace = "http://impl.webservice.spring_cxf.study.hason.com/") 
public class HelloWorldWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.spring_cxf.study.hason.com/", "HelloWorldWebServiceImplService");
    public final static QName HelloWorldWebServiceImplPort = new QName("http://impl.webservice.spring_cxf.study.hason.com/", "HelloWorldWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/spring-cxf/webservice/hello?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorldWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/spring-cxf/webservice/hello?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloWorldWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWorldWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWorldWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloWorldWebService
     */
    @WebEndpoint(name = "HelloWorldWebServiceImplPort")
    public HelloWorldWebService getHelloWorldWebServiceImplPort() {
        return super.getPort(HelloWorldWebServiceImplPort, HelloWorldWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldWebService
     */
    @WebEndpoint(name = "HelloWorldWebServiceImplPort")
    public HelloWorldWebService getHelloWorldWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldWebServiceImplPort, HelloWorldWebService.class, features);
    }

}
