package com.hason.study.spring_cxf.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-23T16:13:16.458+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://webservice.spring_cxf.study.hason.com/", name = "HelloWorldWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCatByUser", targetNamespace = "http://webservice.spring_cxf.study.hason.com/", className = "com.hason.study.spring_cxf.webservice.GetCatByUser")
    @WebMethod
    @ResponseWrapper(localName = "getCatByUserResponse", targetNamespace = "http://webservice.spring_cxf.study.hason.com/", className = "com.hason.study.spring_cxf.webservice.GetCatByUserResponse")
    public java.util.List<com.hason.study.spring_cxf.webservice.Cat> getCatByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.hason.study.spring_cxf.webservice.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://webservice.spring_cxf.study.hason.com/", className = "com.hason.study.spring_cxf.webservice.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://webservice.spring_cxf.study.hason.com/", className = "com.hason.study.spring_cxf.webservice.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllCats", targetNamespace = "http://webservice.spring_cxf.study.hason.com/", className = "com.hason.study.spring_cxf.webservice.GetAllCats")
    @WebMethod
    @ResponseWrapper(localName = "getAllCatsResponse", targetNamespace = "http://webservice.spring_cxf.study.hason.com/", className = "com.hason.study.spring_cxf.webservice.GetAllCatsResponse")
    public com.hason.study.spring_cxf.webservice.StringCatMap getAllCats();
}
